-- ============================================================
-- POS2SAP — staffs table (HQ_FAMTIME shared POS database)
-- ============================================================
--
-- DO NOT INSERT OR CREATE rows in `staffs` from this project.
-- The `staffs` table is owned by the POS system (StaffID is NOT identity).
-- POS2SAP login only READS existing staff rows (see AuthController.cs).
--
-- Use existing POS users only, e.g. StaffLogin = 'vtec'.
-- To enable web login, ensure the user has:
--   Activated = 1, Deleted = 0
--   StaffPassword = BCrypt hash OR legacy SHA1 (auto-upgraded on login)
--
-- If test rows were accidentally inserted with StaffID = 0 (e.g. 'admin'
-- from an older version of this script), remove them manually:
--
--   DELETE FROM staffs WHERE StaffID = 0 AND StaffLogin IN ('admin', 'user1');
--
-- Never run INSERT on production HQ_FAMTIME staffs.

PRINT 'seed-staffs.sql: no-op — use existing POS staff accounts only.';
